# int build & anything that doesn't match below
[build]
  command = sed -i s/CRDS_APP_CLIENT_ENDPOINT_PLACEHOLDER/$CRDS_APP_CLIENT_ENDPOINT/g netlify.toml

[[redirects]]
  from = "/*"
  to = "CRDS_APP_CLIENT_ENDPOINT_PLACEHOLDER/media:splat"
  status = 301
